### ISSUE TITLE
Failed to construct kafka producer

### ISSUE THREAD

**Issue by metaversed** [gschmutz/iot-vehicle-tracking-demo#2]
Getting below message after entering "docker run trivadis/iot-truck-simulator '-s' 'KAFKA' '-h' $PUBLIC_IP '-p' '9092' '-f' 'CSV' "-t" "sec""

Hi, @gschmutz , are we expected to make any configuartion other than specified in workshop ? 

docker run trivadis/iot-truck-simulator '-s' 'KAFKA' '-h' $PUBLIC_IP '-p' '9092' '-f' 'CSV' "-t" "sec"
Unable to find image 'trivadis/iot-truck-simulator:latest' locally
latest: Pulling from trivadis/iot-truck-simulator
e7c96db7181b: Already exists
f910a506b6cb: Pull complete
b6abafe80f63: Pull complete
debb6005af60: Pull complete
af85f7b0f10a: Pull complete
fcc35f0441dd: Pull complete
Digest: sha256:58d5de296e0018e4b779be96027393f4a2179520b5a944f1dd8bee5993a9384e
Status: Downloaded newer image for trivadis/iot-truck-simulator:latest
iot-truck-simulator: 9092: unrecognized option

/app/resources/routes/midwest
com.hortonworks.labutils.SensorEventsParam@15aeb7ab
log4j:WARN No appenders could be found for logger (com.hortonworks.simulator.impl.domain.transport.route.TruckRoutesParser).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Number of Emitters is .....23
akka://EventSimulator/user/eventCollector
[EventSimulator-akka.actor.default-dispatcher-3] INFO org.apache.kafka.clients.producer.ProducerConfig - ProducerConfig values:
	acks = all
	batch.size = 16384
	bootstrap.servers = [-p:]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id =
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = false
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

[EventSimulator-akka.actor.default-dispatcher-3] INFO org.apache.kafka.clients.producer.KafkaProducer - [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms.
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:430)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:298)
	at com.hortonworks.solution.KafkaSensorEventCollector.connect(KafkaSensorEventCollector.java:33)
	at com.hortonworks.solution.KafkaSensorEventCollector.<init>(KafkaSensorEventCollector.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at akka.util.Reflect$.instantiate(Reflect.scala:45)
	at akka.actor.NoArgsReflectConstructor.produce(Props.scala:364)
	at akka.actor.Props.newActor(Props.scala:255)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: -p:
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:60)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:49)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:408)
	... 22 more

**Comment by metaversed** [comment]
It seems like we need to run "docker run --network docker_default trivadis/iot-truck-simulator '-s' 'KAFKA' '-h' 'broker-1' '-p' '9092' '-f' 'CSV'" 

and i see the consumer something like below

1566046817075,69,11,1090292248,Normal,38.65,-90.2,3844029735808517411
1566046817612,48,17,1565885487,Normal,38.65,-90.21,3844029735808517411
1566046817834,47,18,1390372503,Normal,39.78,-89.66,3844029735808517411
1566046817878,20,19,1927624662,Normal,37.69,-97.36,3844029735808517411
1566046817915,12,16,1961634315,Normal,40.7,-89.52,3844029735808517411
1566046817954,44,30,1594289134,Normal,41.62,-93.58,3844029735808517411
1566046817994,24,29,371182829,Normal,37.69,-97.36,3844029735808517411
1566046818038,78,20,24929475,Normal,41.62,-93.58,3844029735808517411
1566046818096,87,13,1962261785,Normal,41.62,-93.58,3844029735808517411
1566046818148,108,32,160779139,Normal,35.19,-90.04,3844029735808517411
1566046818170,65,12,160779139,Normal,38.62,-90.15,3844029735808517411
1566046818208,16,10,1090292248,Normal,38.64,-90.18,3844029735808517411
1566046818229,92,15,927636994,Normal,35.19,-90.04,3844029735808517411
1566046818264,50,14,1384345811,Normal,37.03,-94.58,3844029735808517411
1566046818312,51,24,137128276,Normal,38.65,-90.2,3844029735808517411
1566046818336,84,23,160405074,Normal,40.7,-89.52,3844029735808517411
1566046818366,67,31,1567254452,Normal,37.03,-94.58,3844029735808517411
1566046818393,38,25,1198242881,Normal,38.62,-90.15,3844029735808517411
1566046818413,91,27,987179512,Normal,38.65,-90.21,3844029735808517411
1566046818436,105,21,1198242881,Normal,37.03,-94.58,3844029735808517411
1566046818467,19,22,1594289134,Normal,35.19,-90.04,3844029735808517411
1566046818499,54,26,1325562373,Normal,38.64,-90.18,3844029735808517411
1566046818527,75,28,160405074,Normal,39.78,-89.66,3844029735808517411
1566046820479,12,16,1961634315,Normal,40.86,-89.91,3844029735808517411
1566046820521,44,30,1594289134,Normal,41.69,-93.36,3844029735808517411
1566046820573,48,17,1565885487,Normal,38.75,-90.41,3844029735808517411
1566046820644,69,11,1090292248,Normal,39.1,-89.74,3844029735808517411

**Comment by gschmutz** [comment]
yes this is one way to solve it (using --network) and to be honest maybe event the better way. I am using the PUBLIC_IP environment variable, and it that one is set, then the --network should not be necessary. Will add that as an option to the README
